server.port=8080


spring.profiles.active=${ENV:dev}
# Judge0 (already present)
judge0.api.url=https://ce.judge0.com/submissions?base64_encoded=false&wait=true
judge0.api.key=a9c468920dmshace36dcf82e1c3fp1466f6jsn01564649ea84

# ---- MySQL / JPA ----



# ===== JWT Configuration =====
app.jwt.secret=MyUltraStrongSecretKey_1234567890_Dikshant_Editor_Project_2025
app.jwt.expiration-ms=86400000





